### ISSUE TITLE
2.0 hasn't been pushed to npm

### ISSUE THREAD

**Issue by realityking** [inspect-js/is-descriptor#6]
npm still reports 1.0.2 as the most current version

**Comment by SnarkBoojum** [comment]
Hmmm... releases get tagged here, but don't get pushed to npm... isn't there a contradiction here?

**Comment by jonschlinkert** [comment]
There was a reason I didn't publish this to NPM, or I published it and unpublished it right away. I'm trying to remember, but I'll have to look into it again.

**Comment by ljharb** [comment]
v2.0.0 was apparently unpublished, v3.0.0 is the latest.
